/**
 Copyright (C) 2009-2011. ViniSketch SARL - David Thevenin

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/

var application_proto = new Object ();

application_proto.__nagivation_graph = null;

/**
 *  All application inherit from Application class.<br/>
 *  This is the root component from which all other components (widgets, ...)
 *  are dependent on.
 *
 *  @extends Page
 *  @class
 *  All application inherit from Application class. <br/>
 *  This is the root component from which all other components (widgets, ...)
 *  are dependent on.
 *  <p>
 *  The class offers you a set of usefull method for laoding
 *  Javascript or CSS, know the current GUI orientation...
 *  <p>
 *  You should not create your own Application instante, because it is
 *  automatically generated by ViniSketch Designer.
 *
 *  @author David Thevenin
 *
 *  @constructor
 *  Main constructor
 *  @name Application
 *
 *	@param {string} config the configuration stucture [mandatory]
*/
function application_constructor (config)
{
  this.apply ('Page', '_constructor', config);
  
  Application_applications [this.id] = this;
};
application_proto._constructor = application_constructor;

/**
 * @private
 */
var Application_applications = new Object ();

/**
 *  Exit form the application
 *  <br/>
 *
 *  @name exit
 *  @function
 *  @memberOf Application.prototype
 */
function application_exit ()
{
  if (close)
  {
    close ();
  }
}
application_proto.exit = application_exit;

/*****************************************************************
 *             Class declaration
 ****************************************************************/

var Application = Class.create ('Application', application_proto);
Class.extend ('Application', 'Page');